### ISSUE TITLE
Demande de mise a jour.

### ISSUE THREAD

**Issue by Ptitcoeur59580** [saniho/apiFreeBox#1]
Bonjour,

J'utilise le player Devialet et je rencontre unproblème avec les informations.
En effet,  le Channel et le Out sont toujours vide alors que je retrouve bien les information dans le sous menu 'info:'.

`attribution: ''
version: 1.0.0.6
lastSynchro: '2021-12-07T11:58:05.610495'
power_stat: running
package: fr.freebox.tv
package_id: 30
channel: ''
out: ''
info: >-
  {'foreground_app': {'package_id': 30, 'cur_url': '', 'context': {'player':
  {'source': 'rtsp://rtsp-server/fbxtv_priv/stream?namespace=1&service=201',
  'duration': 0, 'livePos': '1638874684117', 'playbackState': 'play',
  'audioIndex': 0, 'audioList': [{'samplerate': 48000, 'type': 'Main', 'pid':
  230, 'channelCount': 2, 'bitrate': '0', 'codec': 'AAC', 'adAvailable': False,
  'uid': 0, 'codecId': 'Aac', 'language': 'fra', 'metadataId': 'None'},
  {'samplerate': 0, 'type': 'Description', 'pid': 231, 'channelCount': 0,
  'bitrate': '0', 'codec': 'AAC', 'adAvailable': False, 'uid': 1, 'codecId':
  'Aac', 'language': 'qad', 'metadataId': 'None'}, {'samplerate': 0, 'type':
  'Main', 'pid': 232, 'channelCount': 0, 'bitrate': '0', 'codec': 'AAC',
  'adAvailable': False, 'uid': 2, 'codecId': 'Aac', 'language': 'qaa',
  'metadataId': 'None'}], 'curPos': '1638874684117', 'subtitleIndex': -1,
  'videoIndex': 0, 'metadata': {}, 'videoList': [{'bitrate': '0', 'codec':
  'H264', 'pid': 220, 'height': 1080, 'framerate': {'den': 1, 'num': 25}, 'uid':
  0, 'width': 1440}], 'subtitleList': [{'codec': 'Teletext subtitle', 'pid':
  250, 'uid': 0, 'language': 'fra', 'type': 'HearingImpaired'}, {'codec':
  'Teletext subtitle', 'pid': 250, 'uid': 1, 'language': 'fra', 'type':
  'Normal'}], 'position': 0, 'mediaState': 'ready', 'sourceHidden': False,
  'minPos': '1638874684117', 'maxPos': '1638874684117'}, 'channel': {'services':
  [{'qualityName': 'auto', 'qualityLabel': 'Automatique', 'name': 'France 2
  (auto)', 'sortInfo': 0, 'id': 977, 'url':
  'rtsp://rtsp-server/fbxtv_priv/stream?namespace=1&service=201', 'typeName':
  'iptv', 'typeLabel': 'ADSL'}, {'qualityName': 'hdplus', 'qualityLabel': 'HD+',
  'name': 'France 2 (HD+)', 'sortInfo': 2, 'id': 976, 'url':
  'rtsp://rtsp-server/fbxtv_priv/stream?namespace=1&service=1321&flavour=hd',
  'typeName': 'iptv', 'typeLabel': 'ADSL'}, {'qualityName': 'hd',
  'qualityLabel': 'HD', 'name': 'France 2 (HD)', 'sortInfo': 5, 'id': 973,
  'url':
  'rtsp://rtsp-server/fbxtv_priv/stream?namespace=1&service=201&flavour=hd',
  'typeName': 'iptv', 'typeLabel': 'ADSL'}, {'qualityName': 'sd',
  'qualityLabel': 'Standard', 'name': 'France 2 (standard)', 'sortInfo': 6,
  'id': 974, 'url':
  'rtsp://rtsp-server/fbxtv_priv/stream?namespace=1&service=201&flavour=sd',
  'typeName': 'iptv', 'typeLabel': 'ADSL'}, {'qualityName': 'ld',
  'qualityLabel': 'Bas débit', 'name': 'France 2 (bas débit)', 'sortInfo': 7,
  'id': 975, 'url':
  'rtsp://rtsp-server/fbxtv_priv/stream?namespace=1&service=201&flavour=ld',
  'typeName': 'iptv', 'typeLabel': 'ADSL'}], 'isTimeShifting': False,
  'videoIsVisible': True, 'channelName': 'France 2', 'channelNumber': 2,
  'channelType': 'regular', 'bouquetName': 'Freebox TV', 'currentServiceIndex':
  '0', 'channelUuid': 'uuid-webtv-201', 'bouquetType': 'adsl', 'bouquetId': 655,
  'channelSubNumber': 0}}, 'package': 'fr.freebox.tv'}, 'player': {'state':
  {'duration_ms': 0, 'playback_state': 'playing', 'position_ms': 0},
  'capabilities': {'shuffle': False, 'select_srt_track': True, 'seek_forward':
  True, 'play': True, 'select_stream': True, 'start_over': True,
  'select_audio_track': True, 'repeat_all': False, 'next': False, 'record_stop':
  True, 'repeat_one': False, 'stop': True, 'seek_to': True, 'seek_backward':
  True, 'record': True, 'pause': True, 'prev': False}, 'name': 'Freebox TV',
  'last_activity': 1638869077}, 'power_state': 'running'}
unit_of_measurement: ''
friendly_name: myFreeBoxPlayer.17
`

Par ailleurs, compte tenu de l'arriver des packages Netflix et Disney +, il faudrait ajouter dans les sensors :
`            elif (quelPackage == "com.disneyplus"):
                status_counts["out"] = "Disney +"
                status_counts["channel"] = "Disney +"
            elif (quelPackage == "com.netflix"):
                status_counts["out"] = "Netflix"
                status_counts["channel"] = "Netflix"      `

Merci pour votre aide pour le premier point, car je tourne en rond, et j'aimerai faire un lovelace avec le media en cours.

**Comment by saniho** [comment]
je vais regarder pour mettre à jour et te proposer une version de test

**Comment by saniho** [comment]
j'ai livré une rc : 1.0.0.7...si tu peux checker ...

**Comment by Ptitcoeur59580** [comment]
Bonsoir,
Je regarde ça tout de suite

**Comment by Ptitcoeur59580** [comment]
Je n'arrive pas à charger la bêta,
Je fait les changements manuellement, je vous tiens au courant.

Ps : dans les package, j'ai oublié prime vidéo (Amazon)

**Comment by Ptitcoeur59580** [comment]
Ça a l'air de fonctionner 👍

Reste à trouver le moyen de récupérer le 'channelname'

**Comment by saniho** [comment]
voila la version release arrive : 1.0.0.8 et te donnera l'information

**Comment by tdelaux** [comment]
Bonjour,
Cette intégration est vraiment pratique ;-)
Serait-il possible de s'assurer que le "channelname"/"channel" ait toujours une information ?
Aujourd'hui, si la freebox n'est pas sur la télé, le chanelName n'est pas disponible. Et l'utilisation de l'information channel n'est pas très usefriendly si l'on est sur la TV.
Je propose la modification de code suivantes (j'en ai profité pour ajouter prime):

            elif (quelPackage == "fr.freebox.mediaplayer"):
                status_counts["out"] = "mediaplayer"
                status_counts["channel"] = "mediaplayer"
                status_counts["channelName"] = "mediaplayer"
            elif (quelPackage == "fr.freebox.vodlauncher"):
                status_counts["out"] = "vodlaucher"
                status_counts["channel"] = "vodlaucher"
                status_counts["channelName"] = "vodlaucher"
            elif (quelPackage == "com.disneyplus"):
                status_counts["out"] = "Disney +"
                status_counts["channel"] = "Disney +"
                status_counts["channelName"] = "Disney +"
                self._state = "Disney +"
            elif (quelPackage == "com.netflix"):
                status_counts["out"] = "Netflix"
                status_counts["channel"] = "Netflix"
                status_counts["channelName"] = "Netflix"
            elif (quelPackage == "com.youtube.tv"):
                status_counts["out"] = "youtube"
                status_counts["channel"] = "youtube"
                status_counts["channelName"] = "youtube"
            elif (quelPackage == "com.primevideo"):
                status_counts["out"] = "Prime"
                status_counts["channel"] = "Prime"
                status_counts["channelName"] = "Prime"  
            elif (quelPackage == "fr.freebox.home"):
                status_counts["out"] = "home"
                status_counts["channel"] = "home"
                status_counts["channelName"] = "home" 
            else:

**Comment by saniho** [comment]
C est une bonne idée n'hésite pas a proposer une merge request... sinon je l'intègrerai si tu ne sais pas comment faire

**Comment by saniho** [comment]
version 1.0.0.9a disponible en pre-release
dans l'attente de confirmation que tout est ok pour passage en prod

**Comment by Ptitcoeur59580** [comment]
Depuis l'installation je suis en Channel inconnu

Envoyé de mon iPad

Le 7 févr. 2022 à 21:36, saniho ***@***.***> a écrit :

﻿

version 1.0.0.9a disponible en pre-release
dans l'attente de confirmation que tout est ok pour passage en prod

**Comment by tdelaux** [comment]
chez moi, le channel remonte bien.
Sur la TV ou sur une plateforme.

Attention, channel est avec un c minuscule

![image](https://user-images.githubusercontent.com/44919953/152932186-fc848404-fcad-4d65-9260-eed1c4636667.png)
![image](https://user-images.githubusercontent.com/44919953/152932381-fb5e4420-9d41-4aa0-80f9-223386cf1dd4.png)

Par contre, j'ai du réappairer avec la Freebox. j'avais perdu la connexion. + recocher le droit avec le player

**Comment by Ptitcoeur59580** [comment]
Est-ce lié à la devialet ?

[cid:AAE2FAB2-B18B-42B5-B450-834E585BC5EC-L0-001]

Envoyé de mon iPhone

Le 8 févr. 2022 à 07:42, tdelaux ***@***.***> a écrit :

﻿

chez moi, le channel remonte bien.
Sur la TV ou sur une plateforme.

Attention, channel est avec un c minuscule

[image]<https://user-images.githubusercontent.com/44919953/152932186-fc848404-fcad-4d65-9260-eed1c4636667.png>
[image]<https://user-images.githubusercontent.com/44919953/152932381-fb5e4420-9d41-4aa0-80f9-223386cf1dd4.png>

**Comment by tdelaux** [comment]
Ma configuration : Freebox Delta + Devialet.
Peux-tu mettre une capture de ce que tu as dans les outils de développement avec le channel vide ?

**Comment by Ptitcoeur59580** [comment]
﻿Bonjour,

Le channel vide :
[cid:0F0A0A1B-DC71-49F6-A8E0-F94200E5D90B-L0-001]

Alors que myfreebox remonte bien

[cid:DA37ABB6-CACE-4A61-9FC8-076054642E88-L0-001]

Envoyé de mon iPad

Le 8 févr. 2022 à 08:24, tdelaux ***@***.***> a écrit :

﻿

Ma configuration : Freebox Delta + Devialet.
Peux-tu mettre une capture de ce que tu as dans les outils de développement avec le channel vide ?

**Comment by Ptitcoeur59580** [comment]
J'ai trouvé mon erreur,
C'est mon capteur freebox_channel qui n'était plus bon

Envoyé de mon iPad

Le 8 févr. 2022 à 08:24, tdelaux ***@***.***> a écrit :

﻿

Ma configuration : Freebox Delta + Devialet.
Peux-tu mettre une capture de ce que tu as dans les outils de développement avec le channel vide ?

**Comment by saniho** [comment]
Donc plus de pb,?

**Comment by tdelaux** [comment]
Je pense que tu peux clôturer ...

**Comment by Ptitcoeur59580** [comment]
Oui, et passer en prod.

Envoyé de mon iPhone

Le 15 févr. 2022 à 17:14, tdelaux ***@***.***> a écrit :

﻿

Je pense que tu peux clôturer ...

**Comment by saniho** [comment]
done
